### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by delaneyj** [ByteArena/ecs#1]
There doesn't appear to be a licensed. Is it public domain?

**Comment by netgusto** [comment]
Indeed, the LICENSE file was missing, thanks. ECS is licensed under the Creative Commons Attribution-NonCommercial 4.0 International License (see the LICENSE file for details).

**Comment by xtuc** [comment]
We need to update https://github.com/ByteArena/ba/blob/master/LICENSE, ecs isn't listed in it.
